#!/usr/bin/env bash
# Revoke a client certificate and publish a CRL for StrongSwan.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=lib/certs.sh
source "${SCRIPT_DIR}/lib/certs.sh"

usage() {
  cat <<'EOF'
Usage: sudo ./revoke-client.sh NAME

Revoke the client certificate for NAME and publish a CRL that StrongSwan
loads from /etc/ipsec.d/crls. The Apple profile generated by issue-client.sh
does not ask iOS to check revocation; the server enforces the CRL.
EOF
}

name=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      die "Unknown option: $1"
      ;;
    *)
      [[ -z "$name" ]] || die "Unexpected argument: $1"
      name="$1"
      shift
      ;;
  esac
done

[[ -n "$name" ]] || die "Missing client name. Usage: sudo ./revoke-client.sh <name>"

require_root
require_ubuntu
require_cmd openssl
load_config
validate_client_name "$name"

crt="${VPN_CLIENTS_DIR}/${name}/${name}.crt"
[[ -f "$crt" ]] || die "No certificate for ${name} at ${crt}"
revoke_certificate "$crt"
stamp="${VPN_CLIENTS_DIR}/${name}/REVOKED"
printf 'Revoked at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$stamp"
chmod 644 "$stamp"

cat <<EOF
Client certificate revoked.
  Name:        ${name}
  Certificate: ${crt}
  CRL:         ${CRL_PATH}
EOF
